name: API-Web-Performance

on: push

jobs:
  API-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cypress-Test
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./API
          command: npm run test

  Web-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        working-directory: ./Web
        run: npm ci
      - name: Install and run  playwright browsers
        working-directory: ./Web
        run: npx playwright install --with-deps
      - name: Run tests
        working-directory: ./Web
        run: npm run test
        
  Performance-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run performance test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ./Performance/performance-test.js

  

