name: API-Web-Performance

on: push

jobs:
  API-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: cypress-Test
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./API
          command: npm run test



  Performance-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run performance test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: ./Performance/performance-test.js

